[project]
dynamic = ["dependencies"]
name = "buddy"
version = "0.1.0"
requires-python = ">=3.10.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
